# we want to create a container for django+celery and postgres
version: "3"
services:
  database:
    container_name: tenant1_database
    restart: always
    image: postgres:13.6-alpine
    networks:
      - tenant1_network
    environment:
      - POSTGRES_DB=tenant1
      - POSTGRES_USER=tenant1
      - POSTGRES_PASSWORD=tenant1
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    container_name: tenant1_backend
    build: .
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - tenant1_network
    command: 
      - pipenv graph
      - pipenv run gunicorn --version
      - pipenv run gunicorn -b 0.0.0.0:8000 --worker-class=gevent --worker-connections=1000 --workers=2 core.core.wsgi


volumes:
  db_data:

networks:
  tenant1_network:
    driver: bridge
